AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless npm registry

Globals:
  Function:
    Timeout: 10
    MemorySize: 1024

Resources:
  RegistryBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: npm-registry-bucket
      
  RegistryAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: NPMRegistry
      Runtime: dotnet8
      Architectures:
        - arm64
      Environment:
        Variables:
          BUCKET: npm-registry-bucket
      Policies:
        - "AWSLambda_FullAccess"
        - "AmazonS3ReadOnlyAccess"
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            
  RegistryBucketHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: NPMRegistry::NPMRegistry.VersionHandler::Handle
      Runtime: dotnet8
      Architectures:
        - arm64
      Policies:
        - "AWSLambda_FullAccess"
        - "AmazonS3FullAccess"
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref RegistryBucket
            Events:
              - s3:ObjectCreated:*
              - s3:ObjectRemoved:*
